Repository JM-Lemmi/ical-relay, pull requests merged in 2023-04, with the labels that each got.

#155 nilreference in `getEventsByDay()`
  profiles.go
Labels: bug, frontend

#156 Allow events with no location
  handlers.go
Labels: bug

#163 profile name as title & Favicons
  config.go
  config.yml.example
  handlers.go
  templates/edit.html
  templates/head.html
  templates/howto-users.html
  templates/index.html
  templates/modules.html
  templates/monthly.html
  templates/nav.html
  templates/settings.html
  templates/static/css/main.css
  templates/static/media/favicon.svg
  templates/subscribe.html
  templates/unsubscribe.html
Labels: feature, frontend

#166 add URL encoding to notifier Mails
  notifier.go
Labels: bug, notifier

#179 fix config upgrade only getting one rule
  cmd/ical-relay/legacyconfig.go
Labels: bug, backend

#180 fix regex rule upgrade
  cmd/ical-relay/legacyconfig.go
Labels: bug

#174 Weekly view added, renamed monthly->calendar
  cmd/ical-relay/handlers.go
  cmd/ical-relay/profiles.go
  cmd/ical-relay/templates/calendar.html
  cmd/ical-relay/templates/head.html
  cmd/ical-relay/templates/index.html
  cmd/ical-relay/templates/monthly.html
  cmd/ical-relay/templates/settings.html
  cmd/ical-relay/templates/static/js/calendar.js
Labels: frontend

#175 add Profile API
  cmd/ical-relay/api.go
  cmd/ical-relay/config.go
  cmd/ical-relay/handlers.go
Labels: feature, backend
